### PR TITLE
feat: upload 2023 static sites

### PR DESCRIPTION
**Pull request by rockleona**
## Types of changes

* **New feature**

## Description

Add 2023 static sites to code

### CODE REVIEW

**Comment by rockleona** [comment]
Hi @josix , I found this accidentally commits, but I already tried restore as well but failed.
How should I do to prevent this kind of error?

image

**Comment by josix** [comment]
Hi @rockleona, How about reset at your local machine, then force push to update this PR?

> Hi @josix , I found this accidentally commits, but I already tried restore as well but failed. How should I do to prevent this kind of error?
> 
> image

**Comment by rockleona** [comment]
> Hi @rockleona, How about reset at your local machine, then force push to update this PR?
> 
> > Hi @josix , I found this accidentally commits, but I already tried restore as well but failed. How should I do to prevent this kind of error?
> > image

Well, I changed to Ubuntu and redo the process again, and it clone and commit successfully, Windows just troll me so hard......

**Comment by josix** [comment]
Thanks @rockleona LGTM

**Pull request merged**
